### ISSUE TITLE
use mongodb in redux

### ISSUE THREAD

**Issue by ghost** [buckyroberts/React-Redux-Boilerplate#3]
How can use mongodb in react? i can able to fetch directly in component data but i am not able to get record with combineReducers. please provide solution. I used following code for combineReducers :- 

``` javasrcipt
detailReducer = () => {
    Meteor.subscribe('detail');
    var detail = Detail.findOne();
    console.log("-----> ",detail.data)
    return detail.data;
}

export default createContainer(() => {
    Meteor.subscribe('detail');
    var detail = Detail.findOne();
    console.log("-----> ",detail.data)
    return {
        detail: detail.data
    };
}, detailReducer);
```

**Comment by buckyroberts** [comment]
MongoDB is for the back-end (database), React is used for the front-end (client)

Usually how it works is you develop an API, this way you can access the back-end server (and MongoDB data) from the front-end using React. There are a lot of different libraries you can use to make it easier to connect to the API. Axios is a popular one and works really well with React:

https://github.com/mzabriskie/axios
